Repository nvseshaiah2013/hisaab_kitaab_api_spring, pull requests merged in 2024-02, with the labels that each got.

#15 Updated .gitignore file
  .gitignore
Labels: documentation

#16 Feature/containerize spring boot application
  Dockerfile
Labels: enhancement

#17 Updated gitignore to exclude .oci folder
  .gitignore
Labels: enhancement

#18 Configured Mongo Connection
  pom.xml
  src/main/java/com/kitaab/hisaab/ledger/config/CustomMongoDBConnectionConfigurer.java
  src/main/java/com/kitaab/hisaab/ledger/constants/CustomConfigConstants.java
  src/main/java/com/kitaab/hisaab/ledger/util/VaultUtils.java
  src/main/resources/application.yaml
Labels: enhancement

#23 Added documentation links to HELP.md
  HELP.md
Labels: documentation, release-v1

#24 Added logging and rolling appender support
  .gitignore
  pom.xml
  src/main/resources/application.yaml
  src/main/resources/log4j2-spring.xml
Labels: enhancement, release-v1

#21 Configuration of Spring Security and JWT
  pom.xml
  src/main/java/com/kitaab/hisaab/ledger/config/CustomMongoDBConnectionConfigurer.java
  src/main/java/com/kitaab/hisaab/ledger/config/JwtSecret.java
  src/main/java/com/kitaab/hisaab/ledger/config/JwtSecretConfig.java
  src/main/java/com/kitaab/hisaab/ledger/config/SecurityConfig.java
  src/main/java/com/kitaab/hisaab/ledger/config/VaultSecretsConfig.java
  src/main/java/com/kitaab/hisaab/ledger/constants/ApplicationConstants.java
  src/main/java/com/kitaab/hisaab/ledger/constants/CustomConfigConstants.java
  src/main/java/com/kitaab/hisaab/ledger/dto/response/ErrorMessage.java
  src/main/java/com/kitaab/hisaab/ledger/entity/user/User.java
  src/main/java/com/kitaab/hisaab/ledger/filter/JwtFilter.java
  src/main/java/com/kitaab/hisaab/ledger/repository/UserRepository.java
  src/main/java/com/kitaab/hisaab/ledger/service/JwtService.java
  src/main/java/com/kitaab/hisaab/ledger/service/impl/JwtServiceImpl.java
  src/main/java/com/kitaab/hisaab/ledger/service/impl/LoginUserServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: enhancement, release-v1

#26 Added jjwt-impl and jjwt-jackson dependencies
  pom.xml
  src/main/java/com/kitaab/hisaab/ledger/config/SecurityConfig.java
  src/main/java/com/kitaab/hisaab/ledger/repository/UserRepository.java
  src/main/java/com/kitaab/hisaab/ledger/service/impl/LoginUserServiceImpl.java
Labels: bug, release-v1

#30 Added CorsConfigurationSource to fix CORS issue
  src/main/java/com/kitaab/hisaab/ledger/config/SecurityConfig.java
  src/main/resources/application.yaml
Labels: bug, release-v1

#37 maven automatic build
  .github/workflows/maven.yml
Labels: enhancement, release-v1
